### ISSUE TITLE
Say Cog - Error in command

### ISSUE THREAD

**Issue by DragoPrime** [TheDataLeek/Eris-Cogs#59]
I have tried to send a message to a channel but it gives this error in logs. Tried the command with the server name and even with the ID of the server.
![chrome_8h4Tw5HNJu](https://github.com/TheDataLeek/Eris-Cogs/assets/99618256/c400270d-747b-46e2-b716-2ec71ecb6f25)

**Comment by TheDataLeek** [comment]
Thanks for the post! I just updated to the latest version of Red and a lot of bugs snuck in. I'll take a look at this!

**Comment by TheDataLeek** [comment]
Added better error handling on this in the case of a guild not being found. Let me know if you still run into trouble!
